auth_controller:
    type: rest
    name_prefix: auth_
    resource: 'App\Controller\AuthenticationController'

user_controller:
    type: rest
    name_prefix: user_
    resource: 'App\Controller\UserController'

ingredient_controller:
    type: rest
    name_prefix: ingredient_
    resource: 'App\Controller\IngredientController'

dish_controller:
    type: rest
    name_prefix: dish_
    resource: 'App\Controller\DishController'